### ISSUE TITLE
Issue with Polygons that have a too long coordinates list

### ISSUE THREAD

**Issue by Farnaz-Hosseinpour** [pnwairfire/fccsmap#12]
Hi,

I have the geometry polygon information for some of the MTBS fires. I installed and tested the package successfully and was able to run fccsmap for some of them successfully. However, I encounters an error for one fire with polygon type that has a long list of coordinates:
-bash: /ignis1/home/farnaz/.conda/envs/consume/bin/fccsmap: Argument list too long

I attached my command line as a txt file (which is a very long line). I searched online, but I couldn't find useful information. I did select the maximum amount of space for command arguments (ulimit -s 65536), but it was not helpful in solving the issue.

I wonder if you have any experience in this regard, and if you have a solution or workaround?

Thanks,

I invoke my command on Linux Ubuntu bash environment. I also write my command in my Python code to be run by Python3.

[FCCS_map.txt](https://github.com/pnwairfire/fccsmap/files/6749986/FCCS_map.txt)

**Comment by Farnaz-Hosseinpour** [comment]
[](url)

**Comment by jdubowy** [comment]
Thanks for the bug report.  The issue, as you noticed, is due to the limitation of the number of characters you can have in your command.  It's imposed by your shell.

There are two solutions:
 1. Instead of using `./bin/fccsmap`, write your polygon data to separate file, load the data in your own python script, and then import and call the fccsmap package in your script.
 2. Wait for an update which I just coded and will soon publish to be able to specify a separate file containing the polygon data.

**Comment by jdubowy** [comment]
I just published v3.0.1.  You can now specify a separate file containing your data:

**Comment by Farnaz-Hosseinpour** [comment]
Thank you very much for quick reply and fix! It does solve the issue.
